layout_spectrum: 0.1551433
typography_spectrum: 0.7572037
color:
  lightness: 0.1131136
  brandStrength: 0.04135846
  saturation: 0.3169656
  rhythmicContrast: 0.8745595
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: Outdoor Media Partners
